### ISSUE TITLE
Use cases?

### ISSUE THREAD

**Issue by XVincentX** [bbarr/medium#10]
Hey!
I am just entering into the `csp` world and looks good so nice. I'm diving into concepts and the current implementations in Javascript.

Actually I'm struggling a lot finding real use cases where `csp` would fit perfectly, as well some where replacing `Promises` with `csp` would have sense.

Do you, as library author, have anything interesting to share? I would love to implement some of those!

**Comment by bbarr** [comment]
Hey @XVincentX, sorry to take so long to reply.

This might come as a surprise, since I have bothered to write a CSP library, but I have not found many instances where CSP sufficiently simplify my code beyond promises and a focus on simple, quasi-functional coding.

Medium was really written for 2 purposes: to help me grok CSP, and to provide an implementation that was as stripped down and easy to read-the-source-of as possible (so that others can use it to understand CSP, perhaps). I continue to play with it in side-projects, and I have hope that it will provide value in some specific cases, but as yet, I don't have much to suggest here. If I find a use-case, I will be sure to post it in the README somewhere, though, and if anyone else finds a killer use, I would love to hear!

**Comment by XVincentX** [comment]
@bbarr 

I see. Well at least now I know I am not crazy or unable to understand where those concepts can be applied. I was wondering wether you would like to share side projects as well. It might be at least a starting point.

Have a nice day!
