### ISSUE TITLE
Does this work with generator/yield syntax as well?

### ISSUE THREAD

**Issue by trusktr** [bbarr/medium#2]
I'm curious, because Babel 6 async/await is [currently](https://github.com/babel/babel/pull/2908#issuecomment-154900858) [broken](https://github.com/babel/babel/commit/940b86dadbd0151c33c02e89f0b5ff61077c9214#commitcomment-14259015), and I want to write code in generator/yield format that I can convert later, so I thought if I can find a CSP channel lib that is compatible with both formats then it'll be easier.

**Comment by bbarr** [comment]
@trusktr Sorry to say, no, this won't work with generator/yield only. The core explicitly relies on the async/await keywords.

I am using async/await and Babel 6 on a few projects right now without problem.. I tend to use Babel presets: 'es2015' and 'stage-1', instead of loading things as individual plugins, if that helps you at all. And noting that 12 days has gone by since you wrote this, perhaps it those issues are fixed already.. hope so!
